version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/hashicorp/go-retryablehttp
    versions:
    - 0.6.8
  - dependency-name: gopkg.in/gographics/imagick.v3
    versions:
    - 3.3.0
