on: [push, pull_request]
name: Build
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version: "1.20.3"
      - run: go build ./cmd/dotaspirit
