on: [push, pull_request]
name: Build
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run
        uses: actions/setup-go@v3
        with:
          check-latest: true
          go-version: "1.19"
      - run: go build ./cmd/go-ps3syscon